baseURL = 'https://ray-che.com/'
languageCode = 'en-us'
title = 'Ray X. Che'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = true

# Intro on main page, content is markdown
homeIntroTitle = 'Welcome!'
homeIntroContent = """
I am a Computer Science Ph.D. student working on AI. I am currently in Illinois, USA.

I share my poetry, sketches, and technical articles here. Enjoy your stay!
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = "Jan 2, 2006"

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "email"
url = "mailto:xijiache@gmail.com"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'github'

# Giscus comments
[params.giscus]
enable = true
repo = "RayCxggg/blog"
repoid = "R_kgDONo0VRw"
category = "Announcements"
categoryid = "DIC_kwDONo0VR84CxEDt"
mapping = "pathname"
theme = "preferred_color_scheme"